### ISSUE TITLE
FSL: problem with randomise_parallel and fsl_sub [IN03009540]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#173] opened 2018-06-05 13:52 UTC
We need to fix the Legion job submission problem with randomise_parallel and fsl_sub. Curently getting the following error:
```
Unable to run job: Job was rejected because job requests unknown queue "short.q"
Exiting.
```

**Comment by owainkenwayucl** [comment] 2018-06-06 12:41
I'm about 90% sure that this is my fault, as when I installed FSL 5.0.10 I just run the script for 5.0.9 and it's quite likely that some changes didn't get carried over.

**Comment by owainkenwayucl** [comment] 2018-06-06 12:45
Looking at the script, I suspect the problem is that at no point is https://github.com/UCL-RITS/rcps-buildscripts/blob/master/fsl-patches/fsl-5.0.9_parallel.patch applied which seems to be what sets all the queue config stuff.

**Comment by balston** [comment] 2018-06-06 13:08
Yes we definitely need a version of these patches applied to  5.0.10.

**Comment by owainkenwayucl** [comment] 2018-06-06 13:17
Right. It looks like `fsl_sub` and `bedpostx` have changed enough that the patches don't work.

**Comment by owainkenwayucl** [comment] 2018-06-06 14:03
Actually, it's not that, the patch doesn't apply on FSL 5.0.9 either:  

```
[ccspapp@login13 fsl]$ patch -p0 -i fsl-5.0.9_parallel.patch 
patching file bin/fsl_sub
Hunk #1 FAILED at 11.
Hunk #2 succeeded at 125 with fuzz 2.
Hunk #4 FAILED at 165.
Hunk #8 FAILED at 273.
Hunk #10 FAILED at 452.
Hunk #11 FAILED at 462.
5 out of 11 hunks FAILED -- saving rejects to file bin/fsl_sub.rej
patching file bin/bedpostx
Hunk #1 FAILED at 10.
Hunk #6 FAILED at 195.
2 out of 8 hunks FAILED -- saving rejects to file bin/bedpostx.rej

```

**Comment by owainkenwayucl** [comment] 2018-06-06 14:16
Right, this commit gives FSL 5.0.9 a patch that can actually be applied: https://github.com/UCL-RITS/rcps-buildscripts/commit/8e6543371d927d0f37a0cb59c6ddd55d24c9d481

**Comment by owainkenwayucl** [comment] 2018-06-06 14:17
Now I need to forward port the changes to 5.0.10.

**Comment by owainkenwayucl** [comment] 2018-06-06 15:15
In the end it was easier(!) to port the changes between 5.0.9 and 5.0.10 to our scripts for `fsl_sub` and `bedpostx` for 5.0.9 than to apply our changes to 5.0.10.

The end result is the same (the main changes are Oxford renaming "Isis" to "Oxford innovation" in the copyright notice, and adding a `-R` option for RAM).

**Comment by owainkenwayucl** [comment] 2018-06-06 15:15
I'm doing a test build on Myriad now since that is largely empty.

**Comment by owainkenwayucl** [comment] 2018-06-06 15:16
https://github.com/UCL-RITS/rcps-buildscripts/commit/2e15bbf423743a832e80f06d37f9f5a35ec50f39

**Comment by owainkenwayucl** [comment] 2018-06-06 15:47
I've applied the patch to Legion - waiting to see if this has resolved the user's problem.

**Comment by owainkenwayucl** [comment] 2018-06-07 10:35
I've tested and `fsl_sub` works correctly now.

Closing.

**Closed by owainkenwayucl** 2018-06-07 10:35 UTC
Labels: Legion, bug
