### ISSUE TITLE
Matlab parpool within a node has intermittent problems

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#55] opened 2016-07-13 13:26 UTC
IN01857030 and IN01867684

There are several issues here.
1. When $TMPDIR is the working directory, the parpool is not created successfully and gives a 'Permission denied' error. This appears to have begun around 7th July. This is reproducible with a simple example.
2. Even when working in Scratch, the user's jobs appear to fall back to serial runs at times. Deleting and recreating the `~/.matlab/R2015a` and `~/.matlab/local_cluster_jobs/R2015a` directories appears to fix this for a time. (`~/.matlab` is a symlink to `~/Scratch/.matlab` so it is writeable).

Local cluster jobs put temporary files in `/tmp` on the node.
There is also the file `~/.matlab/local_cluster_jobs/R2015a/matlab_metadata.mat` in addition to the job-specific files in there, which may be a problem when running multiple jobs using local pools at once.

**Comment by heatherkellyucl** [comment] 2016-07-13 13:32
To test point 1, we have been using qrsh sessions.

```
qrsh -l mem=1G,h_rt=1:0:0 -pe mpi 12 -now no

module load matlab/full/r2015a/8.5
cd $TMPDIR
matlab -nosplash -nodesktop -nodisplay

>> parpool('local',12)
Starting parallel pool (parpool) using the 'local' profile ...
Error using parpool (line 103)
Failed to start a parallel pool. (For information in addition to the causing error, validate the profile
'local' in the Cluster Profile Manager.)
   
Caused by:
    Error using parallel.internal.pool.InteractiveClient>iThrowWithCause (line 667)
    Failed to start pool.
        Error using parallel.Job/createTask (line 277)
        Permission denied
```

If you change directory into Scratch, either inside or outside Matlab, the parpool can be created successfully. However, sometimes it hangs at the creation step with no errors and returns nothing until qrsh runs out of time. I've been running strace to try to find out what is happening here, and Matlab continues to load and check files, but very slowly.

**Comment by heatherkellyucl** [comment] 2016-07-13 14:23
For the $TMPDIR case, stracing file-related calls with 
`strace -f -e trace=file -ostrace_child.out matlab -nosplash -nodesktop -nodisplay`

```
9559  stat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2.diary.txt", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
9559  getcwd("/tmpdir/job/1417513.undefined", 1024) = 30
9559  lstat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2", 0x2b8c23feacb0) = -1 ENOENT (No such file or directory)
9559  getcwd("/tmpdir/job/1417513.undefined", 1024) = 30
9559  stat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2", 0x2b8c23feab80) = -1 ENOENT (No such file or directory)
9559  lstat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2", 0x2b8c23fead80) = -1 ENOENT (No such file or directory)
9559  stat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2", 0x2b8c23feabf0) = -1 ENOENT (No such file or directory)
9559  mkdir("/scratch", 0775)           = -1 EEXIST (File exists)
9559  mkdir("/scratch/scratch", 0775)   = -1 EACCES (Permission denied)
9559  stat("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en_GB/FileManip.xml", 0x2b8c23fea780) = -1 ENOENT (No such file or directory)
9559  stat("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en/FileManip.xml", {st_mode=S_IFREG|0444, st_size=959, ...}) = 0
9559  open("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en/FileManip.xml", O_RDONLY) = 512
9559  stat("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en_GB/legacy_two_part.xml", 0x2b8c23ff5cd0) = -1 ENOENT (No such file or directory)
9559  stat("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en/legacy_two_part.xml", {st_mode=S_IFREG|0444, st_size=68991, ...}) = 0
9559  open("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en/legacy_two_part.xml", O_RDONLY) = 512
9559  stat("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en_GB/MException.xml", 0x2b8c23ff5cd0) = -1 ENOENT (No such file or directory)
9559  stat("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en/MException.xml", {st_mode=S_IFREG|0444, st_size=1149, ...}) = 0
9559  open("/shared/ucl/apps/Matlab/R2015a/full/resources/MATLAB/en/MException.xml", O_RDONLY) = 512
9559  open("/shared/ucl/apps/Matlab/R2015a/full/toolbox/distcomp/cluster/+parallel/+internal/+pool/InteractiveClient.m", O_RDONLY) = 512
9559  open("/shared/ucl/apps/Matlab/R2015a/full/toolbox/distcomp/cluster/+parallel/@Pool/Pool.m", O_RDONLY) = 512
9559  open("/shared/ucl/apps/Matlab/R2015a/full/toolbox/distcomp/cluster/+parallel/@Pool/Pool.m", O_RDONLY) = 512
9559  open("/shared/ucl/apps/Matlab/R2015a/full/toolbox/distcomp/cluster/+parallel/+internal/+pool/doParpool.m", O_RDONLY) = 512
9559  open("/shared/ucl/apps/Matlab/R2015a/full/toolbox/distcomp/cluster/parpool.m", O_RDONLY) = 512
9559  lstat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2.state.mat", {st_mode=S_IFREG|0644, st_size=8, ...}) = 0
9559  stat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job2.state.mat", {st_mode=S_IFREG|0644, st_size=8, ...}) = 0
```

The only permission denied error in there is 
`9559  mkdir("/scratch/scratch", 0775)   = -1 EACCES (Permission denied)`

Which doesn't make a great deal of sense.

I was trying to strace a successful run in Scratch for comparison to see where the parpool section happens, but that has consistently made it hang at pool creation. Part of output, though it keeps going on to do other things.

```
61081 stat("/home/cceahke/.smpd", {st_mode=S_IFREG|0600, st_size=22, ...}) = 0
61081 open("/home/cceahke/.smpd", O_RDWR) = -1 EACCES (Permission denied)
61081 stat("/home/cceahke/.smpd", {st_mode=S_IFREG|0600, st_size=22, ...}) = 0
61081 open("/home/cceahke/.smpd", O_RDWR) = -1 EACCES (Permission denied)
61081 stat("/home/cceahke/.smpd", {st_mode=S_IFREG|0600, st_size=22, ...}) = 0
61081 open("/home/cceahke/.smpd", O_RDWR) = -1 EACCES (Permission denied)
60792 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR|O_CREAT|O_EXCL, 0600) = 533
61108 +++ exited with 0 +++
61113 +++ exited with 0 +++
61114 +++ exited with 0 +++
60991 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 501
60947 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 505
60991 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 501
60947 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 505
60929 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 509
60929 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 509
60836 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR <unfinished ...>
60899 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 513
60899 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 513
60836 <... open resumed> )              = 521
60844 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 517
60836 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 521
60844 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 517
60835 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 525
60835 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 525
61081 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR <unfinished ...>
60791 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 529
60791 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 529
61081 <... open resumed> )              = 489
61081 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 489
61054 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 493
61054 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 493
61019 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 497
61019 open("/dev/shm/mpich_shar_tmphhmG7p", O_RDWR) = 497
60792 unlink("/dev/shm/mpich_shar_tmphhmG7p") = 0
60772 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x2ae33ab2f980} ---
60380 +++ exited with 0 +++
60327 stat("/home/cceahke/.flexlmrc",  <unfinished ...>
60962 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60999 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
61028 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
61059 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
61086 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60934 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60904 stat("/home/cceahke/.flexlmrc",  <unfinished ...>
60840 stat("/home/cceahke/.flexlmrc",  <unfinished ...>
60839 stat("/home/cceahke/.flexlmrc",  <unfinished ...>
60904 <... stat resumed> {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60847 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60840 <... stat resumed> {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60839 <... stat resumed> {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60796 stat("/home/cceahke/.flexlmrc",  <unfinished ...>
60327 <... stat resumed> {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60796 <... stat resumed> {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60795 stat("/home/cceahke/.flexlmrc", {st_mode=S_IFREG|0755, st_size=46, ...}) = 0
60324 lstat("/scratch/scratch/cceahke/.matlab/local_cluster_jobs/R2015a/Job5.state.mat", {st_mode=S_IFREG|0644, st_size=7, ...}) = 0
```

**Comment by heatherkellyucl** [comment] 2016-07-13 15:43
...

I started matlab inside screen, on the same node the parpool had just failed, from $TMPDIR in order to attach ltrace to it, as you can't ltrace the matlab startup script. Ltrace was making it hang, so I killed the ltrace. It then successfully created the pool. I exited and ran matlab again, still in screen, and it succeeded again. I exited screen and it failed. I ran screen again and it still failed.

Success:

```
[cceahke@node-u07a-023 1437015.undefined]$ matlab -nosplash -nodesktop -nodisplay

                                                                              < M A T L A B (R) >
                                                                    Copyright 1984-2015 The MathWorks, Inc.
                                                                    R2015a (8.5.0.197613) 64-bit (glnxa64)
                                                                               February 12, 2015


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.


        Academic License

>> parpool('local',12)
Starting parallel pool (parpool) using the 'local' profile ... connected to 12 workers.

ans = 

 Pool with properties: 

            Connected: true
           NumWorkers: 12
              Cluster: local
        AttachedFiles: {}
          IdleTimeout: 30 minute(s) (30 minutes remaining)
          SpmdEnabled: true

>> pwd

ans =

/tmpdir/job/1437015.undefined
```

**Comment by heatherkellyucl** [comment] 2016-07-13 15:50
The ltrace output I did get is mostly doing these over and over in various orders.

```
31124 __gxx_personality_v0(1, 2, 0x432b2b00, 0xb79f09d0 <unfinished ...>
31528 SYS_getegid32(0xc82fbf54, 128, 5, 0 <unfinished ...>
31527 SYS_madvise1(0xc82f9c54, 137, 1, 0xc577d170 <unfinished ...>
31526 SYS_times(494, 3152, 0xc567c2ec, 0xc567c050 <unfinished ...>
31525 SYS_listxattr("\372\373\374\375\376\377", 0xc8352000, 8192 <unfinished ...>
```

**Comment by heatherkellyucl** [comment] 2016-07-13 15:56
Race condition with parpool startup?

**Comment by heatherkellyucl** [comment] 2016-07-14 09:58
There definitely was a problem with matlabpools when running multiple jobs using the local cluster at once: https://rc.fas.harvard.edu/resources/documentation/software/matlab-pct-simultaneous-job-problem/

parpools seem to write more files in /tmp on the node - the only shared file appears to be `~/.matlab/local_cluster_jobs/R2015a/matlab_metadata.mat` as mentioned in the first post here, but it may be worth it for the original user to set a unique JobStorageLocation for each job and see if that stops the occasional corruptions.

This does not address the $TMPDIR problem above as I am only running one instance of Matlab at a time when that happens.

**Comment by heatherkellyucl** [comment] 2016-07-15 11:13
User is specifying a different JobStorageLocation for each job now, but is getting this for a large proportion of jobs:

```
{Error using parpool (line 103)
Failed to start a parallel pool. (For information in addition to the causing
error, validate the profile 'local' in the Cluster Profile Manager.)

Caused by:
Error using parallel.internal.pool.InteractiveClient>iThrowWithCause (line
667)
Failed to start pool.
Error using parallel.Cluster/createCommunicatingJob (line 92)
The storage metadata file is corrupt. Please delete all files in the
JobStorageLocation and try again.
}
```

http://pace.gatech.edu/matlab suggests that having multiple parpools start up simultaneously is still a problem even in this case and suggests putting a random wait in. The user's jobs were all submitted together from an automatic job creation script and on to empty paid nodes, so would have started at once. 

The `matlab_$JOB_ID` directories were all created at the same time, but have no contents. They should each have a matlab_metadata.mat in them.

**Comment by heatherkellyucl** [comment] 2016-08-03 09:45
We are going to wait until we have Matlab 2016b, and then document and send in all the various Matlab issues to Mathworks.

**Comment by heatherkellyucl** [comment] 2016-10-26 10:34
This was suggested as a possible solution to local parpools interfering with each other: you can set a different preference directory for each job, and then each one will have its own local_cluster_jobs directory. 

```
export MATLAB_PREFDIR=/home/username/Scratch/matlab_prefs/$JOB_ID
```
Put that in your jobscript followed by your normal matlab execution command. Matlab should then create that directory when it starts. This can be cleaned up after the job, either inside the jobscript or manually if you want to check any of its contents. If you're using an array job you'll want to use something like`$JOB_ID.$SGE_TASK_ID` to have a unique directory for each task.

**Comment by heatherkellyucl** [comment] 2016-12-02 13:40
Modification:

> The local scheduler data folder is one level up from the preferences in a folder called "local_scheduler_data" or "local_cluster_jobs".

So you want to create a directory structure that has the job ID one directory higher up:

```
export MATLAB_PREFDIR=/home/username/Scratch/matlab_prefs/$JOB_ID/prefs
```

**Comment by owainkenwayucl** [comment] 2018-01-19 11:17
We should really report this to Mathworks.

**Comment by ikirker** [comment] 2019-01-15 18:08
So, I was trying to reproduce this on Legion using Matlab R2018b.

It looks like each separate parpool tries to create a separate set of state files in `~/.matlab/local_cluster_jobs/R2018b/` and then there's also a general metadata file:

```
Job1
Job1.common.mat
Job1.diary.txt
Job1.in.mat
Job1.jobout.mat
Job1.out.mat
Job1.state.mat
Job5
Job5.common.mat
Job5.diary.txt
Job5.in.mat
Job5.jobout.mat
Job5.out.mat
Job5.state.mat
[...]
matlab_metadata.mat
```

Running `inotifywait` on the directory (recursive, monitoring), suggests that every time you create a parpool, it creates a new one of these file sets and then tries to delete them when the parpool is destroyed -- I have some left over because I have parpools that haven't cleanly terminated, but everything still seems to work.

I haven't been able to cause any visible problems by creating multiple parpools on the same host or on different hosts yet.

**Comment by ikirker** [comment] 2019-01-17 12:49
Further testing reveals that changing `MATLAB_PREFDIR` doesn't change where Matlab looks for the `local_cluster_jobs` directory.

**Comment by ikirker** [comment] 2019-01-25 11:13
*Might* have been fixed in 2018(a|b)? (Could try replicating the error with an older version to check.)

As a racy problem it's not actually possible to trigger reliably?

**Closed** 2022-05-09 08:50 UTC
Labels: bug, Legion
