### ISSUE TITLE
CP2K 7.1 & 6.1 (IN:03088095)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#189] opened 2018-07-17 09:09 UTC
A user has requested that we update CP2K to version 6.1.

**Comment by ikirker** [comment] 2018-07-30 11:22
Curious why the 5.1 build script uses SVN to download rather than downloading from SourceForge...

<https://downloads.sourceforge.net/project/cp2k/cp2k-6.1.tar.bz2>

**Comment by heatherkellyucl** [comment] 2018-07-30 11:40
(Being the person who did it, I'm not sure if sourceforge was down/not updated at that point, or if it was just because all the other download methods are more prominent on their page).

**Comment by ikirker** [comment] 2018-08-09 12:51
Okay, this build is enormous. I ran out of space in `/dev/shm` (because a bunch of other leftover builds were hogging space, but still.)

**Comment by ikirker** [comment] 2018-10-12 15:39
```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 22
Number of WRONG   tests 0
Number of CORRECT tests 2960
Number of NEW     tests 18
Total number of   tests 3000
GREPME 22 0 2960 18 3000 X
--------------------------------------------------------------------------
Regtest took 13315.00 seconds.
--------------------------------------------------------------------------
Fri Oct 12 16:21:04 BST 2018
*************************** testing ended ********************************
```

:(

Looks like segfaults? Might be running out of memory.

Also there's one RUNTIME FAIL that looks like the test doesn't work -- it tries to restart from a file that doesn't exist.

**Comment by heatherkellyucl** [comment] 2019-10-07 07:54
CP2K 6.1 requested again in IN:03921680 - need to check what was going on with the test segfaults.

**Comment by heatherkellyucl** [comment] 2019-10-31 14:21
Another request in IN:03965563

**Comment by ikirker** [comment] 2019-11-08 17:04
Added the serial and OpenMP binary distributions for the meanwhile.

**Comment by hillary-b** [comment] 2019-11-14 10:56
Another request IN:03985982

**Comment by owainkenwayucl** [comment] 2019-12-19 16:54
I've been working on this for benchmarking purposes and I've uncovered a lot off issues building the parallel version and getting it to pass its tests.  I've been using the toolchain builder that it comes with to build all the dependencies except OpenMPI and OpenBLAS, the former for obvious reasons and the latter because the version the toolchain builder tries to use doesn't compile.

I've found two sets of bugs related to floating point on the Skylake/Cascade Lake machines.

1) `libxsmm` which is an optional library built by default by the toolchain builder fails in the regression tests with floating point exceptions.  These are reported as runtime failures (usually an MPI misconfiguration).  This happens with all versions of GCC.  Building without `libxsmm` seems to resolve this.

2) By default the arch files that the toolchain builder generates enable `--ffast-math` which at least with `-march=native` in GCC 9.2 and probably 7.x as well generates code which has enough floating point wrongness that CP2K detects cubic bounding boxes as non-cubic and throws errors again reported as runtime failures.

I have a build with GCC 4.9.2 and therefore no AVX512 (it's supported by the compiler but there's no corresponding arch as far as I know?) in my home directory of the `.popt` version which resolves the two issues above, so I'll take over this issue and script this up and deploy it either tomorrow or when I get back after Christmas.

**Comment by owainkenwayucl** [comment] 2019-12-19 17:00
```
Number of FAILED  tests 0                                                                                          |
Number of WRONG   tests 0                                                                                          |
Number of CORRECT tests 3047                                                                                       |
Number of NEW     tests 19                                                                                         |
Total number of   tests 3066
GREPME 0 0 3047 19 3066 X
--------------------------------------------------------------------------
Regtest took 694.00 seconds.
--------------------------------------------------------------------------
Thu Dec 19 16:56:41 GMT 2019
*************************** testing ended ********************************
```

That build passes all tests.

**Comment by owainkenwayucl** [comment] 2019-12-19 17:34
Interestingly, building with the Intel compilers and the HPC Advisory Council's set of options creates a lot of failures like this:

```
 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/    The specified OLD file <BASIS_SET> cannot be opened. It does not  *
 *    |                         exist. Data directory path:                    *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                   common/cp_files.F:399 *
 ******************************************************************************
```

**Comment by owainkenwayucl** [comment] 2020-01-06 13:30
Deployed as `cp2k/6.1/ompi/gnu-4.9.2` on everything.

**Comment by owainkenwayucl** [comment] 2020-01-06 13:37
All requesting users contacted.

**Comment by owainkenwayucl** [comment] 2020-01-06 16:25
Because life in HPC is like this, CP2K 7.1 came out literally over Christmas.

So I'll build that while CP2K's processes are in my mind.

Interestingly, the Intel version is not having the file reading issue that 6.1 had...

**Comment by owainkenwayucl** [comment] 2020-01-07 12:05
Intel 2019 build:

```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2859
Number of NEW     tests 0
Total number of   tests 2859
GREPME 0 0 2859 0 2859 X

Summary: correct: 2859 / 2859; 12min
Status: OK

--------------------------------------------------------------------------
Regtest took 726.00 seconds.
--------------------------------------------------------------------------
Tue Jan  7 12:02:34 GMT 2020
*************************** testing ended ********************************
```

On the other hand I'm having all kinds of issues with the toolchain script which is preventing me building a GCC version.

**Comment by owainkenwayucl** [comment] 2020-01-07 12:21
On the GNU side this is what I've run into: https://github.com/cp2k/cp2k/issues/709

**Comment by dev-zero** [comment] 2020-01-07 12:53
Some remarks wrt building: `-ffast-math` should not be in the toolchain anymore and is known to break things. If you still see the flag cropping up I'd suggest to rebuild the complete toolchain (`rm -rf build/ install/` when in `tools/toolchain`), please also note that we previously enabled `-ffast-math` when building the compiler, so the toolchain-built compiler enabled it automatically (when building the toolchain with `--with-gcc` or `--install-all`).

For the libxsmm errors (if they still persist with 7.1 and latest libxsmm) @hfp might want to know. Using libxsmm is recommended.

The data directory path issue should not be compiler-related. What you usually want is to define `-D__DATA_DIR=...` to where you're going to finally place the contents of the `data/` directory to make sure when a user specifies a basis set, pseudopotential file, that directory is searched for the file.
The regtest in v7.1 should still use data files in the source directory by [setting the `CP2K_DATA_DIR` environment variable](https://github.com/cp2k/cp2k/blob/7a9f3165805724bca0cab22f5f3da0285d17d48f/tools/regtesting/do_regtest#L244).

Please also note that some Intel compilers are [known to be broken](https://www.cp2k.org/dev:compiler_support) and that when building with Intel it is advised to use `-fp-model precise` (see [this arch file](https://github.com/cp2k/cp2k/blob/master/arch/Linux-x86-64-intel-regtest.psmp) for a maintained example).

**Comment by owainkenwayucl** [comment] 2020-01-07 13:03
@dev-zero Thanks - we do the main builds for our users with GCC, I've just been testing with the Intel compiler to see if it's possible/there are performance benefits to justify changing, because, as you note, there are lots of issues with CP2K and the Intel compilers!

Doing a GCC build of 7.1 with libxsmm and will report back wrt regression tests.

**Comment by owainkenwayucl** [comment] 2020-01-07 13:41
@dev-zero the newer version of `libxsmm` in 7.1 works fine.

**Comment by owainkenwayucl** [comment] 2020-01-07 14:12
Right.  I'm just going to see if I can work out why elpa was unhappy and then script + deploy 7.1 on all resources.

**Comment by owainkenwayucl** [comment] 2020-01-07 14:41
Ok, the elpa issue looks likely to be due to our old gcc:

```
configure:4147: mpicc -O2 -ftree-vectorize -g -fno-omit-frame-pointer -march=native  -I'/home/uccaoke/Source/cp2k-7.1-elpa/tools/toolchain/install/openblas-0.3.6/include'  -mavx2 -mfma -msse4 -mavx512f -mavx512dq -mavx512cd -mavx512bw  -Wl,--enable-new-dtags  -L'/home/uccaoke/Source/cp2k-7.1-elpa/tools/toolchain/install/openblas-0.3.6/lib' -Wl,-rpath='/home/uccaoke/Source/cp2k-7.1-elpa/tools/toolchain/install/openblas-0.3.6/lib' -L'/home/uccaoke/Source/cp2k-7.1-elpa/tools/toolchain/install/scalapack-2.0.2/lib' -Wl,-rpath='/home/uccaoke/Source/cp2k-7.1-elpa/tools/toolchain/install/scalapack-2.0.2/lib'  conftest.c -lscalapack -lopenblas >&5
gcc: error: unrecognized command line option '-mavx512dq'
gcc: error: unrecognized command line option '-mavx512bw'
```

**Comment by owainkenwayucl** [comment] 2020-01-07 15:37
Elpa is fine.  We used (in the 4.1 era) to build with Quip so testing that now.

**Comment by hfp** [comment] 2020-01-07 16:48
thank you for considering LIBXSMM!

The reported issue about LIBXSMM "fails in the regression tests with floating point exceptions" is likely due to enabling FPEs as part of the compiler flags. It may not be the best idea to manipulate the FP environment when building production code. Enabling FPEs (or perhaps additional changes) can harm performance of the resulting binary.

The issue was recognized and resolved in [LIBXSMM 1.10](https://github.com/hfp/libxsmm/releases/tag/1.10), which is mentioned in the "IMPROVEMENTS / CHANGES" part of the release notes (_Zero-mask unused register parts to avoid false positives with enabled FPEs_). If you want to confirm that the issue you ran into is the one resolved in v1.10, you may test with v1.9 vs v1.10.

---
Prior to v1.10, these FPEs were seen as false positives. An uninitialized part of an AVX-512 register was never involved into results due to properly masking registers in all calculations. There was never an incorrect result due to this problem. Further, most tools (even today) do consider AVX-512 masks when performing certain kinds of runtime analysis. Therefore our resolution was to zero-mask registers and to never rely on junk-data even for unused parts of an AVX-512 register.

**Comment by owainkenwayucl** [comment] 2020-01-08 10:43
@hfp no problem - and thanks for the in depth explanation!

**Comment by owainkenwayucl** [comment] 2020-01-08 14:08
CP2K 7.1 deployed.

**Comment by owainkenwayucl** [comment] 2020-01-13 16:03
Right. It looks like some of our users need libxsmm in 6.1.  On that basis, I'm going to try a build with a newer, fixed libxsmm.

**Comment by hfp** [comment] 2020-01-13 16:21
@owainkenwayucl If you ever want a second source of HOWTO build CP2K, I am maintaining a [step-by-step guide](https://xconfigure.readthedocs.io/cp2k/#step-by-step-guide) for both current and previous release.

**Comment by owainkenwayucl** [comment] 2020-01-16 11:34
Libxsmm builds for 6.1 deployed overnight on all systems.  Users notified.

**Closed** 2020-01-24 11:25 UTC
Labels: Done?, Grace, Legion, Myriad, Thomas, Update
