### ISSUE TITLE
Install request for Myriad: TensorFlow 2.1 upgrade

### ISSUE THREAD

**Issue by ISipi** [UCL-RITS/rcps-buildscripts#326] opened 2020-01-27 14:38 UTC
Hi, could it be possible to get TF 2.1 upgrade along with CUDA 10.1 and CuDNN >= 7.6? The upgrade is more stable than TF 2.0 and fixes some memory leaks -> less strain on Myriad.

**Comment by owainkenwayucl** [comment] 2020-01-28 10:41
Right, it looks like this is the full driver upgrade boogaloo so it may be blocked.

**Comment by owainkenwayucl** [comment] 2020-01-28 10:53
Right, we have driver 418.x on the cards which I believe is enough for 10.1.

**Comment by owainkenwayucl** [comment] 2020-01-28 11:56
Updated Cuda, now cudnn.

**Comment by owainkenwayucl** [comment] 2020-01-29 10:54
CUDNN done.

**Comment by owainkenwayucl** [comment] 2020-01-29 11:36
The version of eigen it uses no longer compiles  on our systems.

So that's fun.

**Comment by owainkenwayucl** [comment] 2020-01-29 11:40
https://github.com/tensorflow/serving/issues/1497

**Comment by owainkenwayucl** [comment] 2020-01-29 11:42
Basically whatever I do to fix this will make things more difficult for Tensorflow users so I need to decide on a strategy to minimise this.

**Comment by owainkenwayucl** [comment] 2020-01-29 13:28
I am now in C++ version dependency hell.  Fun times.

**Comment by owainkenwayucl** [comment] 2020-01-31 10:47
[Note: I'm not installing from `pip` because the Tensorflow wheels for Python 3.7.x are compiled on Ubuntu 16.04 which has a newer GLIBC than RHEL 7 and therefore don't work]

**Comment by Kelkka7** [comment] 2020-01-31 12:08
I'm glad it's nothing too complicated 🙄

**Comment by owainkenwayucl** [comment] 2020-01-31 12:23
Basically Google couldn't work out how to get Python 3.7.x to build on their Ubuntu 14.04 machines that they were using for builds (i tried on a VM and it was trivial) so they moved to 16.04 for the wheels for 3.7 which means no-one using RHEL or CentOS 7 can use their wheels.

It's a pita.

**Comment by owainkenwayucl** [comment] 2020-02-10 14:23
Some leads to investigate here: https://github.com/tensorflow/tensorflow/issues/35867

**Comment by owainkenwayucl** [comment] 2020-02-10 15:00
Both leads dead ends :(

**Comment by Kelkka7** [comment] 2020-02-11 09:20
I thought it would have been as simple to install as TF2, which has already been installed. 

As a temporary work around, is it completely out of the question to have a VM running inside Myriad with a newer OS and TF2.1? I realise others may want to utilise TF2.1 as well, but then the access to the VM could be queued?

**Comment by owainkenwayucl** [comment] 2020-02-11 10:20
My colleague has been looking at Nvidia's containers which work on singularity, and do seem to work on Myriad so that may be a suitable workaround as soon as Nvidia build a tensorflow 2.1 container.

**Comment by owainkenwayucl** [comment] 2020-02-11 10:36
A lot of the problem is not tensorflow itself, it's that the build tool that Google wrote, bazel, pulls new versions of all the packages tensorflow depends on and it's actually building those that are the issue - the primary sources of problems being:

1) New version of llvm
2) New version of Eigen (Eigen is always a problem whem compiling tensorflow and I've never understood why as outside of Bazel it's fine)
3) New version of Swig

It's those that are tripping up.

**Comment by Kelkka7** [comment] 2020-06-19 13:23
Hi Owain, 

There's a new build TF 2.2 that uses Bazel 2.0 - perhaps that'll help?

**Comment by owainkenwayucl** [comment] 2020-11-17 11:40
I think a better path for this in future might be for us to use NGC - https://ngc.nvidia.com/

I know one of my team members looked at this a couple of months ago and we can run them via Singularity.

**Comment by owainkenwayucl** [comment] 2022-02-09 11:45
Things have moved on and Tensorflow wheels now work on rhel 7.

Deploying 2.8.0 and closing ticket.

**Closed by owainkenwayucl** 2022-02-09 11:45 UTC
Labels: App install, Thomas, Update, Myriad, Kathleen
