### ISSUE TITLE
Postgis bug

### ISSUE THREAD

**Issue by willu47** [UCL-RITS/rcps-buildscripts#53] opened 2016-07-01 10:38 UTC
When trying to create the postgis extension within a new postgres database, I get the following error:
```
Traceback (most recent call last):
  File "superpyrate/db_setup.py", line 18, in <module>
    main()
  File "superpyrate/db_setup.py", line 15, in main
    db.create()
  File "/home/ucftpw2/pyrate/pyrate/repositories/aisdb.py", line 159, in create
    tb.create()
  File "/home/ucftpw2/pyrate/pyrate/repositories/aisdb.py", line 271, in create
    cur.execute("CREATE EXTENSION IF NOT EXISTS postgis")
psycopg2.InternalError: could not load library "/shared/ucl/apps/postgres+postgis/9.5.3+2.2.2/gnu-4.9.2/lib/postgis-2.2.so": libimf.so: cannot open shared object file: No such file or directory
```

**Comment by willu47** [comment] 2016-07-01 10:40
A minimum (non-) working example to raise the error:

```
module unload compilers
module load compilers/gnu/4.9.2
module load perl/5.22.0
module load python/2.7.9
module load json-c/0.12/gnu-4.9.2
module load libxml2/2.9.4
module load cunit/2.1-3
module load pcre2/10.21
module load hdf/5-1.8.15/gnu-4.9.2
module load netcdf/4.3.3.1/gnu-4.9.2
module load gdal/2.0.0
module load libtool/2.4.6
module load graphicsmagick/1.3.21
module load ghostscript/9.16/gnu-4.9.2
module load fftw/3.3.4/gnu-4.9.2
module load gmt/5.1.2
module load proj.4/4.9.1
module load postgres+postgis/9.5.3+2.2.2/gnu-4.9.2

export PGDATA=$HOME/Scratch/data
export DBHOSTNAME=localhost
export DBNAME=test_aisdb
export DBUSER=$USER
export DBUSERPASS=

# Initialise the database server
initdb -U $USER

# Spin up the database server
pg_ctl -l $HOME/Scratch/pg_log -w start
createdb $DBNAME
psql -U $USER -c "create extension postgis" $DBNAME
```

**Comment by ikirker** [comment] 2016-07-01 14:30
Hmmm.

When I try the MNWE above, I get the following:

```
$ psql -U $USER -c "create extension postgis" $DBNAME
ERROR:  could not load library "/shared/ucl/apps/postgres+postgis/9.5.3+2.2.2/gnu-4.9.2/lib/postgis-2.2.so": libgeos_c.so.1: cannot open shared object file: No such file or directory
```

Which can be fixed by inserting, at the end of the module loading:

```
module load geos/3.5.0/gnu-4.9.2
```

That's my mistake, I appear to have accidentally omitted GEOS from the list of dependencies in the module file. 

Once I do that, it runs happily.

The problem you're seeing from your Python script looks like a separate issue, probably caused by building with the Intel math libraries and then the module configuration being set such that those libraries are no longer in the `LD_LIBRARY_PATH`.

**Comment by ikirker** [comment] 2016-07-01 14:35
I've fixed the `postgres+postgis/9.5.3+2.2.2/gnu-4.9.2` module to add the `geos` dependency, but that won't fix your Intel math libraries issue.

**Comment by ikirker** [comment] 2016-07-01 14:39
To clarify: nothing in the build I made should use Intel's `libimf.so`: it should be (and is, as far as I know) a pure GCC tools build. If Psycopg's C components have been build with the Intel compilers, though, that could cause that problem.

**Comment by willu47** [comment] 2016-07-01 16:09
Thanks a lot Ian!

**Closed** 2016-07-01 16:50 UTC
Labels: bug
